server:
  port: 8100
  servlet:
    context-path: /user

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    druid:
      # 连接池配置
      initial-size: 2
      min-idle: 1
      max-active: 3
      # 连接等待超时时间
      max-wait: 10000
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com:
      springboot:
        mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl